
package daoc.soapclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Emp", targetNamespace = "http://soapjaxws.daoc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Emp {


    /**
     * 
     * @return
     *     returns java.util.List<daoc.soapclient.Empleado>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmpleados", targetNamespace = "http://soapjaxws.daoc/", className = "daoc.soapclient.GetAllEmpleados")
    @ResponseWrapper(localName = "getAllEmpleadosResponse", targetNamespace = "http://soapjaxws.daoc/", className = "daoc.soapclient.GetAllEmpleadosResponse")
    @Action(input = "http://soapjaxws.daoc/Emp/getAllEmpleadosRequest", output = "http://soapjaxws.daoc/Emp/getAllEmpleadosResponse")
    public List<Empleado> getAllEmpleados();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createEmpleado", targetNamespace = "http://soapjaxws.daoc/", className = "daoc.soapclient.CreateEmpleado")
    @ResponseWrapper(localName = "createEmpleadoResponse", targetNamespace = "http://soapjaxws.daoc/", className = "daoc.soapclient.CreateEmpleadoResponse")
    @Action(input = "http://soapjaxws.daoc/Emp/createEmpleadoRequest", output = "http://soapjaxws.daoc/Emp/createEmpleadoResponse")
    public void createEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns daoc.soapclient.Empleado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmpleado", targetNamespace = "http://soapjaxws.daoc/", className = "daoc.soapclient.GetEmpleado")
    @ResponseWrapper(localName = "getEmpleadoResponse", targetNamespace = "http://soapjaxws.daoc/", className = "daoc.soapclient.GetEmpleadoResponse")
    @Action(input = "http://soapjaxws.daoc/Emp/getEmpleadoRequest", output = "http://soapjaxws.daoc/Emp/getEmpleadoResponse")
    public Empleado getEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
